# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170725_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='skill',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Skill'),
        ),
    ]
