# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projects.Position'),
            preserve_default=False,
        ),
    ]
