# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-19 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170719_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='projects.Project'),
        ),
    ]
