# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-17 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(to='projects.Skill'),
        ),
    ]
