# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-18 18:03
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_upload_path, verbose_name='Avatar picture'),
        ),
    ]
