# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, unique=True),
        ),
    ]
